Update otoproxy.yml

diff --git a/.github/workflows/otoproxy.yml b/.github/workflows/otoproxy.yml
--- a/.github/workflows/otoproxy.yml
+++ b/.github/workflows/otoproxy.yml
@@ -15,8 +15,19 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check GH_TOKEN
+        run: |
+          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
+            echo "Error: GH_TOKEN is not set. Please add GH
+            the GH_TOKEN secret in the repository settings."
+            exit 1
+          fi
+          echo "GH_TOKEN is set."
+
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.GH_TOKEN }}
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -37,6 +48,4 @@ jobs:
           git config --global user.email "actions@github.com"
           git add all-proxies.txt http-proxies.txt socks4-proxies.txt socks5-proxies.txt blacklist.txt
           git commit -m "Update proxy lists $(date +%Y%m%d_%H%M%S)" || echo "No changes to commit"
-          git push
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/RockyGerunX/OtoProxy.git HEAD:main
